### ISSUE TITLE
播放不了音乐

### ISSUE THREAD

**Issue by SplitGemini** [BYJRK/LyricEditor#1]
mp3音频点击播放无反应，之前可以最近不知道发生了什么就不行了

**Comment by BYJRK** [comment]
> mp3音频点击播放无反应，之前可以最近不知道发生了什么就不行了

你好，请问你使用的是 release 中编译好的，还是自己编译的？是任意 mp3 文件都没有办法播放吗？

**Comment by SplitGemini** [comment]
自己编译以及release中都不行，任意mp3 都不行

**Comment by SplitGemini** [comment]
我给你发了邮件[suomikoto@outlook.com](suomikoto@outlook.com)，没想到你回复那么快。

复述一下我发现的问题：在加载完音频文件后进行'IsMediaAvailable' 检查时会出现'MediaPlayer.HasAudio' 和 'MediaPlayer.NaturalDuration.HasTimeSpan' 都为 false 但是 source 是合法 mp3 文件的情况，我还不知道该怎么解决

**Comment by BYJRK** [comment]
你好，你说的问题我并没有能够复现。能否提供一下你使用的操作系统的版本？

**Comment by SplitGemini** [comment]
Win10 专业版 1909 (build 18363.752)

**Comment by SplitGemini** [comment]
F**k, 我找到原因了，我把Windows Media Player删了
![image](https://user-images.githubusercontent.com/34861918/78669129-5e7d6280-790e-11ea-91f5-cdf2beacbc0c.png)

**Comment by SplitGemini** [comment]
装回来重启就可以了，真是打扰了

**Comment by BYJRK** [comment]
哈哈😂
