### ISSUE TITLE
能否添加拖拽导入m4a文件

### ISSUE THREAD

**Issue by Fluctlight** [BYJRK/LyricEditor#11]
目前只能通过选择所有文件后导入 （或者将后缀改为mp4添加）

**Comment by emako** [comment]
可考虑不限定后缀，使用mediainfo检测是否存在音轨再导入，这样甚至能直接导入视频文件。

**Comment by Charlie4k** [comment]
嗯,同样有这个问题，为啥m4a默认不支持拖入导入.希望能支持~感谢~

**Comment by emako** [comment]
最近重设计一遍，还没开源，支持有音轨就能导入，ffmpeg解码

**Comment by Charlie4k** [comment]
可以拖入了~感恩!
但是导入那里是否也可以一并把m4a加上呢
