### ISSUE TITLE
仅使用毫秒数部分的前两位 Use only the first 2 digits in milliseconds part of LRC

### ISSUE THREAD

**Issue by daoxi** [BYJRK/LyricEditor#3]
如题，希望能添加仅使用毫秒数部分的前2位的选项。

目前该软件使用[mm:ss.xxx]格式，虽然有“时间取近似值”的选项，但歌词仍使用3位毫秒数。

而[标准的LRC歌词格式](https://zh.wikipedia.org/wiki/LRC%E6%A0%BC%E5%BC%8F)应该是[mm:ss.xx]（毫秒部分只有2位，与 秒/分 相同），因此并不是所有的播放器都支持[mm:ss.xxx]（毫秒部分有3位）的格式。

希望作者可以考虑下

**Comment by BYJRK** [comment]
感谢你的建议！目前这个问题已在[最新版本](https://github.com/BYJRK/LyricEditor/releases/tag/2.0.4)中修复。

**Comment by daoxi** [comment]
> 感谢你的建议！目前这个问题已在[最新版本](https://github.com/BYJRK/LyricEditor/releases/tag/2.0.4)中修复。



感谢修复，测试了下在从3位毫秒数切换到2位毫秒数时是截位而不是四舍五入(其实截位挺好的，而且在两种毫秒数间切换也仍能保留原来切换前的第3位毫秒数)，所以UI提示的“时间取两位近似值”以及悬停时提示的“...四舍五入...”是不是应该相应的修改描述？或者如果能把“四舍五入转换”和“截位切换”两个功能分开来做可能是更完善的方法。

还有之前[v2.0](https://github.com/BYJRK/LyricEditor/releases/tag/2.0)时的字体挺好的啊，新版的字体看上去像是全部加粗了，导致笔画比较密集的字无法很好的显示(因为字体笔画太粗又不能调字体大小，容易糊成一团黑的)，请问可以考虑修改回原来的字体或者添加一个字体选项吗？
