### ISSUE TITLE
批量偏移时间轴时的计算错误 Miscalculation bug when batch shifting timestamps

### ISSUE THREAD

**Issue by daoxi** [BYJRK/LyricEditor#4]
如题，在之前[规范了2位毫秒数以使其符合LRC格式标准](https://github.com/BYJRK/LyricEditor/issues/3)后，在v2.0.4中勾选“时间取两位近似值”时，若对
`[00:01.10]`
批量偏移`-0.01`(秒)，得到的结果是
`[00:01.90]`
而不是正确情况下的
`[00:01.09]`

估计这bug和“**时间取两位近似值**”选项有关系，顺带问下之前[另一议题下询问的关于3位毫秒数切换到2位毫秒数的问题](https://github.com/BYJRK/LyricEditor/issues/3#issuecomment-1098545622)是不是因为议题已经关闭了没有看到呀...？

**Comment by BYJRK** [comment]
你好，非常感谢你的建议！

非常抱歉，前段时间由于上海封城等原因，暂无瑕顾及。我会在后续对此进行修复

**Comment by BYJRK** [comment]
你好，为什么正确情况下应该是 `.09`？是否应该是 `.89`？

**Comment by BYJRK** [comment]
> 如题，在之前[规范了2位毫秒数以使其符合LRC格式标准](https://github.com/BYJRK/LyricEditor/issues/3)后，在v2.0.4中勾选“时间取两位近似值”时，若对 `[00:01.10]` 批量偏移`-0.01`(秒)，得到的结果是 `[00:01.90]` 而不是正确情况下的 `[00:01.09]`

你好，为什么正确情况下应该是 `.09`？是否应该是 `.89`？

**Comment by daoxi** [comment]
> > 如题，在之前[规范了2位毫秒数以使其符合LRC格式标准](https://github.com/BYJRK/LyricEditor/issues/3)后，在v2.0.4中勾选“时间取两位近似值”时，若对 `[00:01.10]` 批量偏移`-0.01`(秒)，得到的结果是 `[00:01.90]` 而不是正确情况下的 `[00:01.09]`
> 
> 你好，为什么正确情况下应该是 `.09`？是否应该是 `.89`？

你好，你好像误解我的意思了，我是说对时间戳`[00:01.10]`进行偏移`-0.01`秒(也就是减去`[00:00.01]`)，而**不是**对`[00:01.90]`进行偏移(实际上`[00:01.90]`是软件中**偏移后**得到的时间戳(并且该结果是错误的)，而**不是偏移前**的时间戳)。

`[00:01.10]`-`[00:00.01]`=`[00:01.09]` 这样可以理解吗？(但软件中结果却是错误的`[00:01.90]`，可能是因为把`[00:01.090]`(正确结果的三位毫秒数版本)进行了错误的转换吧)

**Comment by BYJRK** [comment]
了解。问题已经在[最新版本](https://github.com/BYJRK/LyricEditor/releases/tag/2.1.0)中解决
