### ISSUE TITLE
无法拖动导入flac

### ISSUE THREAD

**Issue by NestorRay** [BYJRK/LyricEditor#5]
1. 无法通过拖动导入flac格式的文件，目前只能选择文件显示所有文件后导入
2. 导入后不能播放？(可能是我的问题 : (  )

**Comment by NestorRay** [comment]
第二个问题在已关闭的issue中找到了解决办法
**把本机的Windows Media Player删掉了**
不好意思打扰了

**Comment by BYJRK** [comment]
你好，问题已经修复，请下载[最新版本](https://github.com/BYJRK/LyricEditor/releases)
